name: Feature Request
description: Suggest a new feature for Noscli
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this feature solve?
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've thought about?
